version: "3.9"

services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-whishper}
      - POSTGRES_PASSWORD=${DB_PASS:-whishper}
      - POSTGRES_DB=whishper
    volumes:
      - ./whishper_data/db_data/ferret:/var/lib/postgresql/data

  mongo:
    image: ghcr.io/ferretdb/ferretdb
    restart: on-failure
    expose:
      - 27017
    env_file:
      - .env
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://${DB_USER:-whishper}:${DB_PASS:-whishper}@postgres:5432/whishper
    command: ["--telemetry=disable"]

  whishper:
    environment:
      FERRETDB_ENABLED: "true"
